default: &default
  adapter: postgresql

development:
  <<: *default
  database: llb_development

test:
  <<: *default
  database: llb_test
  min_messages: warning

production:
  <<: *default
database: llb_production
