# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e9ce27775d9848b03f517e449d2baca36b341bbea729d5aedf03af7c41b6d8bf2dca64cbbff17a826f63d6fc1dc3e277553d7db3461e8ba110a507c5374f808e

test:
  secret_key_base: 89587bbc57ae69a8db2b8c30ab155d510e20967b3bb54bbceb2f7a186e71ede4f0cf509070e9f3c385dac899f0af1166e9a01b9ea8a31d7e3974a97ba9cd1416

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
